name: Client Side Unit Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  client:
    strategy:
      matrix:
        node-version: [14.5.x]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}


      - name: Run and test client
        working-directory: client
        run: |
          npm install
          npm start &
          npm run test:unit
        env:
          CI: true
          API_URI: http://localhost:5000/

